SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

DROP SCHEMA IF EXISTS `db_lista_pessoa` ;

CREATE SCHEMA IF NOT EXISTS `db_lista_pessoa` DEFAULT CHARACTER SET utf8 ;

USE `db_lista_pessoa` ;

CREATE TABLE IF NOT EXISTS `db_lista_pessoa`.`tb_pessoa` (
  `id_pessoa` INT NOT NULL AUTO_INCREMENT,
  `nm_pessoa` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_pessoa`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `db_lista_pessoa`.`tb_filho` (
  `id_filho` INT NOT NULL AUTO_INCREMENT,
  `id_pessoa` INT NOT NULL,
  `nm_filho` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_filho`))
ENGINE = InnoDB;